matrix:
  include:
    - os: osx
      env: ACTION=iOS
    - os: osx
      env: ACTION=tvOS
    - os: osx
      env: ACTION=carthage
    - os: osx
      env: ACTION=coverage

language: objective-c
osx_image: xcode7.2

script:
  - make install-$ACTION && make test-$ACTION
