language: objective-c

before_install: 
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script: 
- xctool clean build -project EasyTimer.xcodeproj -scheme EasyTimer CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
- xctool test -project EasyTimer.xcodeproj -scheme EasyTimerTests
